CREATE TABLE IF NOT EXISTS "User" (
    "uid" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "created" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated" DATETIME NOT NULL
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "Password" (
    "hash" BLOB NOT NULL,
    "salt" BLOB NOT NULL,
    "uid" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "updated" DATETIME NOT NULL,
    CONSTRAINT "Password_uid_fkey" FOREIGN KEY ("uid") REFERENCES "User" ("uid") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Session" (
    "sid" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "hash" BLOB NOT NULL,
    "salt" BLOB NOT NULL,
    "uid" INTEGER NOT NULL,
    "created" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Session_uid_fkey" FOREIGN KEY ("uid") REFERENCES "User" ("uid") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "Session_uid_idx" ON "Session"("uid");
